services:
  api:
    image: ghcr.io/aau-p9s/workload-api:latest
    hostname: workload-api
    environment:
      WORKLOAD.ADDR: 0.0.0.0
      WORKLOAD.PORT: 8123

    ports:
      - 8123:8123

  generator:
    image: ghcr.io/aau-p9s/workload-generator:latest
    environment:
      GENERATOR.API.ADDR: workload-api
      GENERATOR.API.PORT: 8123
      GENERATOR.PORT: 8124

    ports:
      - 8124:8124
