services:
  api:
    image: ghcr.io/aau-p9s/workload-api:test
    hostname: workload-api
    environment:
      WORKLOAD_ADDR: 0.0.0.0
      WORKLOAD_PORT: 8123

    ports:
      - 8123:8123

  generator:
    image: ghcr.io/aau-p9s/workload-generator:test
    environment:
      GENERATOR_API_ADDR: workload-api
      GENERATOR_API_PORT: 8123
      GENERATOR_PORT: 8124
      GENERATOR_X: 10
      GENERATOR_Y: 10
      GENERATOR_MIN: 2000
      GENERATOR_MAX: 50

    volumes:
      - "/var/agg_minute.csv:/var/agg_minute.csv"

    ports:
      - 8124:8124
