services:
  api:
    image: ghcr.io/aau-p9s/workload-api:latest
    hostname: workload-api
    environment:
      WORKLOAD_ADDR: 0.0.0.0
      WORKLOAD_PORT: 8123

    ports:
      - 8123:8123

  generator:
    image: ghcr.io/aau-p9s/workload-generator:latest
    environment:
      GENERATOR_API_ADDR: workload-api
      GENERATOR_API_PORT: 8123
      GENERATOR_PORT: 8124

    ports:
      - 8124:8124
