name: Create and publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aau-p9s/workload

jobs:
  publish:
    strategy:
      matrix:
        image: [ api, generator ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Log in
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: enable emulation
        run:  docker buildx create --use &&
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes &&
              docker buildx inspect --bootstrap

      - name: add env vars
        run: |
          echo "sha=$(git rev-parse --short $GITHUB_SHA)" >> "$GITHUB_ENV"

      - name : Build and push Docker latest image
        uses: docker/build-push-action@v3
        with:
          context: {{ matrix.image }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-{{ matrix.image }}:latest
          platforms:
            linux/amd64

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: {{ matrix.image }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-{{ matrix.image }}:${{ env.sha }}
          platforms: 
            linux/amd64

